# Arrays

In [2]:
import numpy as np

In [44]:
from numpy.random import randint

In [49]:
randint(1,10) #generate random int 

9

In [12]:
list = [1,2,3]
arr = np.array(list) #creates a vector
arr

array([1, 2, 3])

In [15]:
list2 = [[1,2],[3,4]]
arr2 = np.array(list2) #creates a matrix
arr2

array([[1, 2],
       [3, 4]])

In [16]:
np.arange(0,10,2) #similar to list range

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5) #zeros vector (also works np.ones())

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,3)) #zeros array, argument = tuple

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.linspace(0,1,10) #creates a vector of 10 values from 0 to 1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
np.eye(5) #diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(3,3) #uniform distribution

array([[0.73384573, 0.25974929, 0.15258266],
       [0.82868583, 0.75299367, 0.52902073],
       [0.84449133, 0.68050867, 0.39058416]])

In [24]:
np.random.randn(3) #standard normal distribution

array([ 0.2011257 , -0.1277283 ,  0.12107254])

In [25]:
np.random.randint(0,11, 3) #random 10 ints

array([8, 0, 2])

In [30]:
arr3 = np.arange(25)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr3.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr4 = np.random.randint(1,51,5)
print(arr4)
print(arr4.max(), arr4.argmax())
print(arr4.min(), arr4.argmin())

[ 1 42 16 24 34]
42 1
1 0


#Other useful methods

In [39]:
arr = np.random.randint(0,11,9)
arr = arr.reshape(3,3)
arr

array([[ 5,  2, 10],
       [ 6,  9,  8],
       [ 8,  2,  0]])

In [41]:
print(arr.shape)
print(arr.dtype)

(3, 3)
int64


#NumPy Indexing and Selection

In [59]:
arr = randint(1,11,9).reshape(3,3)
arr

array([[8, 5, 1],
       [4, 9, 9],
       [3, 9, 2]])

In [61]:
arr[2,2]

2

In [62]:
arr = randint(1,11,5)
arr

array([1, 8, 3, 4, 2])

In [63]:
arr[1:4]

array([8, 3, 4])

In [66]:
arr[1:4] = 99 #broadcasting
arr

array([ 1, 99, 99, 99,  2])

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr_b = arr > 5 #array of booleans 
arr_b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [9]:
arr[arr > 8]

array([9])

#NumPy operations

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [20]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

#Exercises

In [22]:
import numpy as np
arr1 = np.zeros(10)
arr1


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
arr3 = arr2 * 5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [26]:
arr4 = np.arange(10,51, 1)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [29]:
arr5 = np.arange(0,9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr7 = np.random.random(1)
arr7

array([0.83203465])

In [37]:
arr8 = np.random.randn(25).reshape(5,5)
arr8

array([[-0.19220751,  0.30216131,  0.96871641,  0.77733761, -1.55553278],
       [ 1.18126236, -0.69843237, -1.09213769,  1.26531047,  1.96845793],
       [ 0.04282051,  0.47295135,  0.98371286, -0.8496882 ,  0.26740031],
       [ 1.54804198,  1.34612418, -1.33207351, -1.82631875, -1.90760531],
       [-1.27592331,  1.23182426,  0.92785703,  0.05495226,  0.12291211]])

In [38]:
arr9 = np.arange(1,101).reshape(10,10)
arr9 = arr9 / 100
arr9

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [40]:
arr10 = np.linspace(0, 1, 20)
arr10

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])