# Arrays

In [1]:
import numpy as np

In [44]:
from numpy.random import randint

In [49]:
randint(1,10) #generate random int 

9

In [12]:
list = [1,2,3]
arr = np.array(list) #creates a vector
arr

array([1, 2, 3])

In [15]:
list2 = [[1,2],[3,4]]
arr2 = np.array(list2) #creates a matrix
arr2

array([[1, 2],
       [3, 4]])

In [16]:
np.arange(0,10,2) #similar to list range

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5) #zeros vector (also works np.ones())

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,3)) #zeros array, argument = tuple

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.linspace(0,1,10) #creates a vector of 10 values from 0 to 1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
np.eye(5) #diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(3,3) #uniform distribution

array([[0.73384573, 0.25974929, 0.15258266],
       [0.82868583, 0.75299367, 0.52902073],
       [0.84449133, 0.68050867, 0.39058416]])

In [24]:
np.random.randn(3) #standard normal distribution

array([ 0.2011257 , -0.1277283 ,  0.12107254])

In [25]:
np.random.randint(0,11, 3) #random 10 ints

array([8, 0, 2])

In [30]:
arr3 = np.arange(25)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr3.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr4 = np.random.randint(1,51,5)
print(arr4)
print(arr4.max(), arr4.argmax())
print(arr4.min(), arr4.argmin())

[ 1 42 16 24 34]
42 1
1 0


#Other useful methods

In [39]:
arr = np.random.randint(0,11,9)
arr = arr.reshape(3,3)
arr

array([[ 5,  2, 10],
       [ 6,  9,  8],
       [ 8,  2,  0]])

In [41]:
print(arr.shape)
print(arr.dtype)

(3, 3)
int64


#NumPy Indexing and Selection

In [59]:
arr = randint(1,11,9).reshape(3,3)
arr

array([[8, 5, 1],
       [4, 9, 9],
       [3, 9, 2]])

In [61]:
arr[2,2]

2

In [62]:
arr = randint(1,11,5)
arr

array([1, 8, 3, 4, 2])

In [63]:
arr[1:4]

array([8, 3, 4])

In [66]:
arr[1:4] = 99 #broadcasting
arr

array([ 1, 99, 99, 99,  2])